### ISSUE TITLE
Release of Projector Weights

### ISSUE THREAD

**Issue by YFCodeDream** [WisconsinAIVision/ViP-LLaVA#16]
I want to fine-tune the ViP-LLaVA in my data. According to the instruction, I need to download the projector weight of the first stage, but it is displayed in MODEL_ZOO. Could you please release the projector weight? And I want to confirm the detailed steps for fine-tuning on custom datasets. Do I need to go through the Pretrain (feature alignment) stage from scratch? If not, can you publish the model weights after the Pretrain (feature alignment) stage? Thank you very much!

Looking forward to your reply!

**Comment by mu-cai** [comment]
Hi @YFCodeDream Actually, I have already released. Please see the updated doc in MODEL_ZOO. 

Also, all the dataset, checkpoints, and evaluators are here: https://huggingface.co/mucai

**Comment by YFCodeDream** [comment]
Thank you for your prompt reply!
