### ISSUE TITLE
[Question] About Data Augmentation

### ISSUE THREAD

**Issue by ia-gu** [WisconsinAIVision/ViP-LLaVA#17]
### Question

I would like to introduce data augmentation to images (texts too in the near future), but I cannot find transforms.
Where can I introduce data augmentation?
Thanks in advance.

**Comment by mu-cai** [comment]
Hi, 

I guess you are referring that how I edit the images. Here is the code https://github.com/WisconsinAIVision/ViP-LLaVA/blob/main/llava/visual_prompt_generator.py

**Comment by ia-gu** [comment]
Sorry, I meant to refer to common data augmentation methods (e.g., HorizontalFlip(), Normalize()).

I supposed to say that [ https://github.com/WisconsinAIVision/ViP-LLaVA/blob/main/llava/visual_prompt_generator.py]( https://github.com/WisconsinAIVision/ViP-LLaVA/blob/main/llava/visual_prompt_generator.py) does not include them.

**Comment by mu-cai** [comment]
There is no data augmentation. 

For each image, there are only two preprocess steps:
- Padding: https://github.com/WisconsinAIVision/ViP-LLaVA/blob/main/llava/train/train.py#L900
- Normalizetion: https://github.com/WisconsinAIVision/ViP-LLaVA/blob/main/llava/train/train.py#L901, which is hidden in the transformers clip encoder.

**Comment by ia-gu** [comment]
I didn't know that. 
Thanks!!!
