### ISSUE TITLE
[Question] When will the Visual Instruction Tuning data be released?

### ISSUE THREAD

**Issue by XuRui314** [WisconsinAIVision/ViP-LLaVA#3]
### Question

Excellent work, may i ask when will the Visual Instruction Tuning data be released? Thx.

**Comment by mu-cai** [comment]
Hi, the Visual Instruction Tuning data and training guidance will be released within 3-4 days. Thanks for your patience.

**Comment by XuRui314** [comment]
Thx for sharing :)
