### ISSUE TITLE
[Question] Will the code for creating Visual Instruction Tuning dataset be released?

### ISSUE THREAD

**Issue by XuRui314** [WisconsinAIVision/ViP-LLaVA#4]
### Question

Waiting for Visual Instruction Tuning data, and i wonder if the code for generating this dataset will be released, thanks.

**Comment by mu-cai** [comment]
Hi Xurui, both of them will be released. Sorry for the delay due to the Christmas holiday.

**Comment by XuRui314** [comment]
Really sorry to bother you, happy holiday😃!

**Comment by TiantZhang** [comment]
> Hi Xurui, both of them will be released. Sorry for the delay due to the Christmas holiday.

Waiting for Visual Instruction Tuning data, and I wonder if the code for generating this dataset will be released too, thanks~

**Comment by mu-cai** [comment]
Thanks for your patience. Visual Instruction Tuning data, training code, and the the code for generating this dataset are released. @XuRui314 @TiantZhang

**Comment by XuRui314** [comment]
Thx for sharing!
